name: Basic Workflow
on:
  workflow_dispatch

jobs:
  install_depedencies:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3

      - name: Init TF Project
        run: terraform init
      
      - name: Plan TF Project
        run: terraform plan
      
      - name: Apply TF Project
        run: terraform apply -auto-approve
