name: Basic Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Get TF
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Init TF Project
        run: terraform init
      
      - name: Plan TF Project
        run: terraform plan

  tf-apply:
    runs-on: ubuntu-latest
    needs: tf-plan
    outputs:
      tf-results: ${{ steps.tf-output-step.outputs.SOMETHING }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Get TF
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Init TF Project
        run: terraform init
      
      - name: Apply TF Project
        run: |
          terraform apply -auto-approve
      
      - name: Publish TF results output values
        id: tf-output-step
        run: echo "SOMETHING=$(terraform output -json results)" >> "$GITHUB_OUTPUT"
  
  another_job:
    needs: tf-apply
    runs-on: ubuntu-latest
    steps:
      - name: Use Terraform Output
        env:
          TF_APPLY_RESULTS: ${{needs.tf-apply.outputs.tf-results}}
        run: |
          echo "Results: $TF_APPLY_RESULTS"
