name: Basic Workflow
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Get TF
        uses: hashicorp/setup-terraform@v3

      - name: Init TF Project
        run: terraform init
      
      - name: Plan TF Project
        run: terraform plan

  tf-apply:
    runs-on: ubuntu-latest
    needs: tf-plan
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Get TF
        uses: hashicorp/setup-terraform@v3

      - name: Init TF Project
        run: terraform init
      
      - name: Apply TF Project
        id: tf-apply
        run: |
          terraform apply -auto-approve
          echo "::set-output name=results::$(terraform output -json results)"
  
  another_job:
    needs: tf-apply
    runs-on: ubuntu-latest
    steps:
      - name: Use Terraform Output
        run: |
          echo "Results: ${{ needs.tf-apply.outputs.results }}"
