name: Basic Workflow
on:
  workflow_dispatch

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Get TF
        uses: hashicorp/setup-terraform@v3

      - name: Init TF Project
        run: terraform init
      
      - name: Plan TF Project
        run: terraform plan

  tf-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Get TF
        uses: hashicorp/setup-terraform@v3

      - name: Init TF Project
        run: terraform init
      
      - name: Apply TF Project
        run: terraform apply -auto-approve
